---
- name: Gather Juniper SRX Facts using Ansible
  hosts: pynet-sf-srx
  tasks:
    - name: Verifying NETCONF
      wait_for: host={{ ansible_ssh_host }} port=830

    - name: Retrieve Juniper Facts
      junos_get_facts: host={{ ansible_ssh_host }} user={{ juniper_user }} passwd={{ juniper_passwd }}
      register: srx_info

    - name: Print SRX information
      debug: msg="{{ srx_info.facts }}"

