---

- name: Setup my primary ethernet interface
  hosts: arista

  tasks:
    - name: Configure my primary ethernet interface - description
      eos_interface: name=Ethernet4 description="*** IN USE ***"
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https

    - name: Configure my primary ethernet interface - access setup
      # Reset all parameters in case changing from trunk to access port
      eos_switchport: name=Ethernet4 mode=access access_vlan=201 trunk_allowed_vlans=1-4094
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https

